Detect which version of qmake to use when building the autotests and give a 1 second punishment if there are no autotests.

diff --git a/git_hooks/pre-commit_autotest b/git_hooks/pre-commit_autotest
--- a/git_hooks/pre-commit_autotest
+++ b/git_hooks/pre-commit_autotest
@@ -1,8 +1,12 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Check that existing autotests for files that are being commited are not currently failing
 #
-
+QMAKE=qmake
+$QMAKE --version 2>&1 | grep 4.3 > /dev/null
+if [ $? == 0 ] ; then
+    QMAKE=qmake-qt4
+fi
 dir=`dirname $0`
 echo $dir
 for file in `git-diff-index --name-only HEAD | grep .cpp` ; do
@@ -12,10 +16,10 @@ for file in `git-diff-index --name-only HEAD | grep .cpp` ; do
 
         tempfoo=`basename $0`
         TMPFILE=`mktemp -t ${tempfoo}` || exit 1
-        (cd "$dir/../../autotests/$file/"; qmake; make; ./$file >> $TMPFILE)
+        (cd "$dir/../../autotests/$file/"; QMAKE; make; ./$file >> $TMPFILE)
         output=`cat $TMPFILE | grep ' failed,' | sed -e 's/.*passed, //g' -e 's/ failed.*//g'`
         if [ "${output}" != "0" ] ; then
-            echo "Autotests failed for $file, please fix before commiting."
+            echo "Autotests failed for $file, please fix before committing."
             cat $TMPFILE
             rm $TMPFILE
             exit 1
@@ -23,6 +27,8 @@ for file in `git-diff-index --name-only HEAD | grep .cpp` ; do
         rm $TMPFILE
         echo "--checking autotest: $file done--"
     else
-        echo "--missing autotest: $file--"
+        echo "--missing autotest: $file (1 second punishment)--"
+        sleep 1
     fi
 done
+
