Only complain about build failures if there is a Makefile

diff --git a/git_hooks/pre-commit_build b/git_hooks/pre-commit_build
--- a/git_hooks/pre-commit_build
+++ b/git_hooks/pre-commit_build
@@ -5,10 +5,13 @@
 # Feel free to bypass this if the current commit doesn't match the current state.
 
 echo "--Attempting to build--"
-make --quiet
-if [ $? != 0 ] ; then
-    echo "--Build failed, fix failure before commiting--";
-    exit 1
+qmake
+if [ -f Makefile ] ; then
+    make --quiet
+    if [ $? != 0 ] ; then
+        echo "--Build failed, fix failure before commiting--";
+        exit 1
+    fi
 fi
 echo "--Attempting to build pass--"
 
